# Generated by Django 5.2.17 on 2026-08-26 13:43

import django.core.validators
import django.db.models.deletion
import inovasi.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovasi', '0002_alter_periode_min_urusan_yandas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerkasSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berkas', models.FileField(upload_to=inovasi.models.path_bukti, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx', 'mp4'])])),
                ('nama_asli', models.CharField(blank=True, max_length=255)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('diunggah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_berkas', to='inovasi.nilaisid')),
            ],
            options={
                'verbose_name': 'Berkas SID',
                'verbose_name_plural': 'Berkas SID',
                'ordering': ['diunggah_pada'],
            },
        ),
        migrations.CreateModel(
            name='BerkasSPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berkas', models.FileField(upload_to='spd/%Y/')),
                ('nama_asli', models.CharField(blank=True, max_length=255)),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('diunggah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_berkas', to='inovasi.nilaispd')),
            ],
            options={
                'verbose_name': 'Berkas SPD',
                'verbose_name_plural': 'Berkas SPD',
                'ordering': ['diunggah_pada'],
            },
        ),
    ]
