# Generated by Django 5.2.17 on 2026-09-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovasi', '0005_hapus_berkas_lama'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilaisid',
            name='verifikasi_bukti_berkas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nilaisid',
            name='verifikasi_bukti_pilihan',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nilaisid',
            name='verifikasi_bukti_tautan',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
