# Generated by Django 5.2.17 on 2026-09-02 12:09

import django.core.validators
import inovasi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inovasi", "0008_nilaisid_dokumen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="berkassid",
            name="berkas",
            field=models.FileField(
                upload_to=inovasi.models.path_bukti,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        [
                            "pdf",
                            "jpg",
                            "jpeg",
                            "png",
                            "mp4",
                            "mov",
                            "avi",
                            "mkv",
                            "webm",
                            "wmv",
                            "m4v",
                            "3gp",
                            "mpeg",
                            "mpg",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="berkasspd",
            name="berkas",
            field=models.FileField(
                upload_to="spd/%Y/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
